//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:42:13 PM CET 
//


package nl.chb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowcode"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowname"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowtype"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "daowcode",
    "daowname",
    "daowtype"
})
@XmlRootElement(name = "dataowner")
public class Dataowner {

    @XmlElement(required = true)
    protected String daowcode;
    @XmlElement(required = true)
    protected String daowname;
    @XmlElement(required = true)
    protected String daowtype;

    /**
     * Gets the value of the daowcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowcode() {
        return daowcode;
    }

    /**
     * Sets the value of the daowcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowcode(String value) {
        this.daowcode = value;
    }

    /**
     * Gets the value of the daowname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowname() {
        return daowname;
    }

    /**
     * Sets the value of the daowname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowname(String value) {
        this.daowname = value;
    }

    /**
     * Gets the value of the daowtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowtype() {
        return daowtype;
    }

    /**
     * Sets the value of the daowtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowtype(String value) {
        this.daowtype = value;
    }

}
