//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:42:13 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bison.connekt.nl/tmi8/chb/msg", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.chb;
