//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.03 at 12:38:54 PM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bison.connekt.nl/tmi8/chb/msg", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.chb;
