//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.03 at 12:38:54 PM UTC 
//


package nl.chb;

import java.util.GregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}roadcode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}hectometersign" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}greenstop" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}liftedbicyclepath" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "mutationdate",
    "roadcode",
    "hectometersign",
    "greenstop",
    "liftedbicyclepath"
})
@XmlRootElement(name = "quayextraattributes")
public class Quayextraattributes {

    @XmlElement(required = true)
    protected GregorianCalendar validfrom;
    @XmlElement(required = true)
    protected GregorianCalendar mutationdate;
    protected String roadcode;
    protected String hectometersign;
    protected Boolean greenstop;
    protected Boolean liftedbicyclepath;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link GregorianCalendar }
     *     
     */
    public GregorianCalendar getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link GregorianCalendar }
     *     
     */
    public void setValidfrom(GregorianCalendar value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link GregorianCalendar }
     *     
     */
    public GregorianCalendar getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GregorianCalendar }
     *     
     */
    public void setMutationdate(GregorianCalendar value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the roadcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadcode() {
        return roadcode;
    }

    /**
     * Sets the value of the roadcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadcode(String value) {
        this.roadcode = value;
    }

    /**
     * Gets the value of the hectometersign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHectometersign() {
        return hectometersign;
    }

    /**
     * Sets the value of the hectometersign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHectometersign(String value) {
        this.hectometersign = value;
    }

    /**
     * Gets the value of the greenstop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGreenstop() {
        return greenstop;
    }

    /**
     * Sets the value of the greenstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGreenstop(Boolean value) {
        this.greenstop = value;
    }

    /**
     * Gets the value of the liftedbicyclepath property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLiftedbicyclepath() {
        return liftedbicyclepath;
    }

    /**
     * Sets the value of the liftedbicyclepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLiftedbicyclepath(Boolean value) {
        this.liftedbicyclepath = value;
    }

}
