//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:42:13 PM CET 
//


package nl.chb;

import java.time.LocalDateTime;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import nl.chb.binding.LocalDateTimeXmlAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}disabledaccessible"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stepFreeAccess"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}wheelchairAccess"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "disabledaccessible",
    "stepFreeAccess",
    "wheelchairAccess",
    "mutationdate"
})
@XmlRootElement(name = "stopplacedisabledaccessibility")
public class Stopplacedisabledaccessibility {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
    protected LocalDateTime validfrom;
    @XmlElement(required = true)
    protected String disabledaccessible;
    @XmlElement(required = true)
    protected LimitationStatusEnum stepFreeAccess;
    @XmlElement(required = true)
    protected LimitationStatusEnum wheelchairAccess;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
    protected LocalDateTime mutationdate;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(LocalDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the disabledaccessible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabledaccessible() {
        return disabledaccessible;
    }

    /**
     * Sets the value of the disabledaccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabledaccessible(String value) {
        this.disabledaccessible = value;
    }

    /**
     * Gets the value of the stepFreeAccess property.
     * 
     * @return
     *     possible object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public LimitationStatusEnum getStepFreeAccess() {
        return stepFreeAccess;
    }

    /**
     * Sets the value of the stepFreeAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public void setStepFreeAccess(LimitationStatusEnum value) {
        this.stepFreeAccess = value;
    }

    /**
     * Gets the value of the wheelchairAccess property.
     * 
     * @return
     *     possible object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public LimitationStatusEnum getWheelchairAccess() {
        return wheelchairAccess;
    }

    /**
     * Sets the value of the wheelchairAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public void setWheelchairAccess(LimitationStatusEnum value) {
        this.wheelchairAccess = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(LocalDateTime value) {
        this.mutationdate = value;
    }

}
